# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.IntegerField(default=0)),
                ('book_edition', models.CharField(max_length=100)),
                ('seller_email', models.CharField(max_length=200)),
                ('date_time_of_listing', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.CharField(max_length=200)),
                ('buyer_email', models.CharField(max_length=200)),
                ('purchase_date_time', models.DateTimeField()),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.IntegerField(default=0)),
                ('book_edition', models.CharField(max_length=100)),
            ],
        ),
    ]
