# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_edition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 9, 36, 8, 116828)),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='seller_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='book_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='book_edition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='book_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='buyer_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 9, 36, 8, 117649)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='seller_email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
