# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0004_auto_20171201_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='status',
            new_name='book_status',
        ),
        migrations.RenameField(
            model_name='bookdetails',
            old_name='type',
            new_name='book_type',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book_isbn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book_publisher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 12, 51, 37, 480195)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 12, 51, 37, 481614)),
        ),
    ]
