# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0006_auto_20171207_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.CharField(max_length=200)),
                ('buyer_email', models.CharField(max_length=200)),
                ('purchase_date_time', models.DateTimeField()),
                ('book_name', models.CharField(max_length=200)),
                ('book_isbn', models.IntegerField(default=0)),
                ('complaint_nature', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 5, 30, 5, 516435)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 5, 30, 5, 518670)),
        ),
    ]
