# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0008_auto_20171207_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 8, 40, 24, 186704)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='purchase_date_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 8, 40, 24, 188739)),
        ),
    ]
