# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0009_auto_20171207_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 9, 8, 53, 516532)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='purchase_date_time',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 7, 9, 8, 53, 517434)),
        ),
    ]
