# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0013_auto_20171214_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_key',
            field=models.IntegerField(default=-1, max_length=6),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 13, 13, 9, 152390)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 13, 13, 9, 153476)),
        ),
    ]
