# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_books', '0014_auto_20171214_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='date_time_of_listing',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 13, 42, 36, 57831)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='purchase_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 13, 42, 36, 58765)),
        ),
    ]
